openapi: 3.0.3
info:
  title: Langsapp User Commands API
  description: "API for managing users"
  version: 1.0.0

servers:
  - url: https://api.langsapp.net
    description: Production server
  - url: http://localhost:8080
    description: Local server

paths:
  /user:
    post:
      tags:
        - user
      summary: Creates user
      operationId: createUser

      parameters:
        - $ref: 'open_api_common.yaml#/components/parameters/AuthorizationRequired'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-Id'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-System-Name'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-System-Version'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-Model'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-Manufacturer'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-App-Package-Id'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-App-Version'

      requestBody:
        description: User to create
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        required: true

      responses:
        201:
          description: Success - user created
          content: { }
        400:
          description: Bad request
          content: { }
        401:
          description: Unauthorized
          content: { }
        409:
          description: User exists already
          content: { }
        500:
          description: Internal server error
          content: { }

    patch:
      tags:
        - user
      summary: Updates properties of previously created user
      operationId: updateUser

      parameters:
        - $ref: 'open_api_common.yaml#/components/parameters/AuthorizationRequired'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-Id'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-System-Name'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-System-Version'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-Model'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-Device-Manufacturer'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-App-Package-Id'
        - $ref: 'open_api_common.yaml#/components/parameters/Client-App-Version'

      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
        required: true

      responses:
        200:
          description: Success - user updated
          content: { }
        400:
          description: Bad request
          content: { }
        401:
          description: Unauthorized
          content: { }
        404:
          description: User not found
          content: { }
        409:
          description: User not found
          content: { }
        500:
          description: Internal server error
          content: { }

components:
  schemas:
    CreateUserRequest:
      type: object
      properties:
        id:
          description: Globally unique identifier of the user
          type: string
      required:
        - id

    UpdateUserRequest:
      type: object
      description: An object representing complete user
      properties:
        username:
          description: Chosen username
          type: string
        avatar_url:
          description: URL of previously uploaded image of avatar
          type: string
        language_settings:
          $ref: "open_api_common.yaml#/components/schemas/LanguageSettings"
        properties_to_delete:
          description: Array of fields to clear. Note that some of them may not be allowed to be removed
          type: array
          items:
            description: The name of the property to delete
            type: string
            enum: [avatar_url]
            example: avatar_url
