version: '3.3'

services:

  # Consul - service networking solution to automate network configurations,
  # discover services, and enable secure connectivity across any cloud or runtime
  consul:
    container_name: consul
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.72.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    depends_on:
      - tempo
    volumes:
      - ./local-observability/otel-collector/config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
    environment:
      - EXPORT_ENDPOINT=tempo:4317

  tempo:
    container_name: tempo
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./local-observability/tempo/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200"  # tempo
      - "4317"  # otlp grpc

  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./local-observability/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./local-observability/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
