version: '3.3'

services:
  service:
    container_name: service-langsapp
    image: "${CONTAINER_REGISTRY_URL}/langsapp:${LANGSAPP_IMAGE_VERSION}"
    environment:
      - AUTH_IMPLEMENTATION=${AUTH_IMPLEMENTATION}
      - AUTH_KEYCLOAK_BASE_URL=${AUTH_KEYCLOAK_BASE_URL}
      - AUTH_KEYCLOAK_REALM=${AUTH_KEYCLOAK_REALM}
    ports:
      - "8282:8080"
