version: '3.3'

services:
  service:
    container_name: service-langsapp
    image: "${CONTAINER_REGISTRY_URL}langsapp:${LANGSAPP_IMAGE_VERSION}"
    environment:
      - AUTH_IMPLEMENTATION=${AUTH_IMPLEMENTATION}
      - AUTH_KEYCLOAK_BASE_URL=${AUTH_KEYCLOAK_BASE_URL}
      - AUTH_KEYCLOAK_REALM=${AUTH_KEYCLOAK_REALM}
      - OTEL_COLLECTOR_URL=${OTEL_COLLECTOR_URL}
    ports:
      - "8282:8080"
    deploy:
      restart_policy:
        condition: on-failure
        window: 300s
      resources:
        limits:
          cpus: '0.60'
          memory: 500M
        reservations:
          cpus: '0.20'
          memory: 250M
    networks:
      - components_network
networks:
  components_network:
    external: true
