receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: ${env:EXPORT_ENDPOINT}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers:  [ otlp ]
      processors: [ batch ]
      exporters:  [ otlp, logging ]
  telemetry:
    logs:
      level: debug